[project]
name = "streamlit-stockview-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mplfinance>=0.12.10b0",
    "plotly>=5.24.1",
    "streamlit>=1.41.1",
    "ta-lib>=0.5.2",
    "yfinance>=0.2.51",
]
